version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  redis:
    image: redis
    volumes:
      - ./tmp/redis:/data

  web:
    command: bundle exec rails s
    image: davidwessman/synka
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    depends_on:
      - db
    env_file:
      - '.env'
    links:
      - db
    ports:
      - 5000:3000
    volumes:
      - .:/home/user/development/

  sidekiq:
    command: bundle exec sidekiq -C config/sidekiq.yml
    entrypoint: ""
    image: davidwessman/synka
    env_file:
      - '.env'
    environment:
      - PID_FILE=/home/user/development/tmp/pids/sidekiq.pid
    volumes:
      - .:/home/user/development/
