default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  username: postgres
  password:
  database: sync-hours_development

test:
  <<: *default
  username: postgres
  password: ""
  database: sync-hours_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
